version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: school
    volumes:
      - PARAREL_DB_DATA:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_PORT: 5432
      PGADMIN_SERVER_NAME: db
      PGADMIN_SERVER_USERNAME: admin
      PGADMIN_SERVER_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - PG_ADMIN_DATA:/var/lib/pgadmin

  api:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db



volumes:
  PARAREL_DB_DATA:
  PG_ADMIN_DATA:
