version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - PARAREL_DB_DATA:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - PG_ADMIN_DATA:/var/lib/pgadmin

  api:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  PARAREL_DB_DATA:
  PG_ADMIN_DATA:
